### ISSUE TITLE
Heritage

### ISSUE THREAD

**Issue by IzzySoft** [gigabytedevelopers/FireFiles#2]
Just wondering: Is FireFiles based upon [AnExplorer](https://github.com/1hakr/AnExplorer)? The structure of the source code is almost identical (and I see [this fork](https://github.com/enwokoma/AnExplorer) in your list, @enwokoma ), plus peeking into some of the source files, even the content. If so, shouldn't that be mentioned at a prominent place, to give credit where it's due? If you don't, people might cry "plagiarism" and "pirates" – though you put it under the same license, see Apache 2.0 license paragraph 4b+c: you seem to have removed those headers from the files, which would count as violation of 4b+c.

I'm not putting a blame here, just a friendly hint!

**Comment by enwokoma** [comment]
Yes yes! @IzzySoft, FireFiles is based on [AnExplorer](https://github.com/1hakr/AnExplorer) and I did some mentioning in the App's README.md and License Text, do you think it's also necessary to make a text in the About page of FireFiles (within the app)

**Comment by IzzySoft** [comment]
Guess restoring those file headers in the source tree will take more than just a few seconds, so I'd even grant you a few hours or more :wink:

Btw: As RTL support is already present in AnExplorer, FireFiles hardly can be the "only one" having that. Suggested edit: "One of very few file managers to support RTL …"

Apart from that, the edit looks great – a double :+1: :+1: on that!

**Comment by enwokoma** [comment]
Done! Thanks a lot for spotting that out. Your contributions so far has been really helpful to us!

**Comment by IzzySoft** [comment]
@enwokoma Sure! I already said so:

> Guess restoring those file headers in the source tree will take more than just a few seconds, so I'd even grant you a few hours or more 😉

A few days is definitely understandable. Certainly more than one file is affected :stuck_out_tongue_winking_eye:

**Comment by IzzySoft** [comment]
@enwokoma just as a "keep-alive": next weekend starts day after tomorrow :wink:

**Comment by enwokoma** [comment]
Lol! 😂. Am aware of that, still have it in mind, that's why I left it open. 
Unlike me, why I haven't done it up till now is because there are a lot of Tech meetups we (**Gigabyte Developers**) are organizing so that's currently tying everyone down! But we sure hope to get it fixed ASAP!

**Comment by enwokoma** [comment]
I just assigned this to someone else, hopefully he's going to be able to take care of that!

**Comment by IzzySoft** [comment]
:rofl: I know exactly what you mean: so many meetings that's no time left to do the job … I hope you don't mind a weekly reminder, to keep the topic fresh? Won't ping more often than that, and neither call a meeting on it :innocent:

**Comment by enwokoma** [comment]
Cool! If that's okay with you, I really don't mind a weekly reminder! 😂 
Thanks once again for your contributions so far towards the progress of FireFiles!

**Comment by IzzySoft** [comment]
Any time, @enwokoma – and it might not be on the minute, but definitely not shorter termed. With some luck, even completely unnecessary :wink:

**Comment by enwokoma** [comment]
Closing this now...
This has been resolved by @Marcusjnr via #cec6843

**Comment by IzzySoft** [comment]
Thanks, but not so fast @enwokoma – some files have been missed. For example:

https://github.com/1hakr/AnExplorer/blob/master/app/src/main/java/dev/dworks/apps/anexplorer/adapter/SectionedListAdapter.java

```
/*
 * Copyright (C) 2014 Hari Krishna Dulipudi
 * Copyright (C) 2013 The Android Open Source Project
 …
```

Same file in FireFiles is https://github.com/gigabytedevelopers/FireFiles/blob/master/app/src/main/java/com/gigabytedevelopersinc/app/explorer/adapter/SectionedListAdapter.java

```
/*
 * Copyright (C) 2017 Gigabyte Developers Incorporated
 * Copyright (C) 2013 The Android Open Source Project
 …
```

Shouldn't the original credits remain, and yours *added* if you updated the code? At least that's how I understand the license.

**Comment by enwokoma** [comment]
Ok. Thanks for spotting that out! @Marcusjnr might have missed those by mistake. 
I will look into that myself! 😂

**Comment by IzzySoft** [comment]
I didn't say "on purpose" :wink: Maybe to easier spot those, get a copy of the AnExplorer repo and `grep` for above string. Then compare the findings with your code. That should catch most of it.

**Comment by enwokoma** [comment]
Ok.. Would sure do that! Though I may not be able to catch all, but am sure going to update most but not all at all! 
Would probably update 2 or more files and that's all!

**Comment by IzzySoft** [comment]
As many as you can catch – and the more the better. Best if none remains, so nobody can put blame on you. Had you only known before :wink: Tapping my hat for your efforts!
