### ISSUE TITLE
Latest release (v2.3.7) contains ads/tracking even in FDroid build

### ISSUE THREAD

**Issue by IzzySoft** [gigabytedevelopers/FireFiles#3]
I'm shocked! And I hope it is all just a simple mistake. But according to my library scanner, even `FireFiles-Fdroid-release-2.3.7.apk` contains:

* GMS
* Firebase
* Firebase Analytics
* Crashlytics

None of those were present in v2.3.6 – and honestly, with those ingredients it cannot seriously be called `*Fdroid*` as those elements are not acceptable by F-Droid. Could you please check what went wrong there? Meanwhile, I have to raise the AntiFeatures (Tracking, NonFreeDep) in my repo.

**Comment by gigabytedevelopersinc** [comment]
Whoa! That must be some kinda silly mistake from our part!
Please pardon us and give us today to fix this!
@enwokoma, get in here and fix this, u caused this problem!

**Comment by IzzySoft** [comment]
Glad to read it wasn't intended that way – and of course it doesn't solve by just winking your magic wand. Thanks for taking care!

**Comment by enwokoma** [comment]
Good day! Been busy since. Returned now and just saw this! Am so so sorry! This issue emerged once again because of my carelessness! 
I would make some commits before the end of today! 

Thanks @IzzySoft for spotting this one out, it wasn't intentional!

**Comment by IzzySoft** [comment]
@enwokoma it was my scanner spotting it, throwing me a warning about missing AntiFeatures. Same scanner will notify me about obsolete AntiFeatures as soon as they are gone :wink:

Btw: Will you keep the `*Fdroid*` in the name of the "free" APK? As your releases now carry more than one `.apk` I'd need something to tell my updater to pick. I've currently set it on that term, so if you keep this all is fine here. If not, please let me know.

**Comment by enwokoma** [comment]
I have made commits referencing this issue and I can acknowledge from my end that this issue has been fixed!, 
#2 has also been fixed. Please confirm from your end too that it has been fixed as am closing both issues by tomorrow! 
Thanks!

**Comment by IzzySoft** [comment]
I can confirm this issue here seems to be solved – my scanner no longer detects those libraries, and thus I also removed the AntiFeature-tags (changes are just being pushed out right now).

I have no time for an in-depth check of #2 – so I just believe you if you say it's solved. Thanks  for the fast fixes! And are you keeping the term "Fdroid" in the "free APK name"? Because as soon as you switch that again, my auto-updater would no longer be able to catch, so we should agree on something :wink:

**Comment by enwokoma** [comment]
Yes! We would be keeping the term "Fdroid" for a more efficient identification because, we now have a lot of platforms (Amazon, Google Play, Fdroid, plus our Pro version). So, yes, the "Fdroid" term stays as we don't want a situation when things get complicated trying to identify which apk is for F-Droid, Amazon, Free, Pro or Google Play release! 

PS: on the releases page, the apk without the term Fdroid attached to it is just the regular Google Play release which contains the GMS, Firebase, Firebase Analytics and Crashlytics libraries!

**Comment by IzzySoft** [comment]
Thanks Emmanuel! So I figured that right. Considering this issue solved then, and close it.

See you later :wink:
